#!/bin/bash

set -e

POPPLER_VERSION=${POPPLER_VERSION-25.12.0}
POPPLER_TARBALL_URL="https://poppler.freedesktop.org/poppler-${POPPLER_VERSION}.tar.xz"
TEMP_DIR=$(mktemp -d /tmp/poppler.XXXXXXXXXX)

# Install build dependencies
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y cmake libfreetype6-dev libfontconfig1-dev libnss3-dev

cd $TEMP_DIR
echo "Temp dir: $TEMP_DIR"

echo "Downloading $POPPLER_TARBALL_URL"
curl -L $POPPLER_TARBALL_URL | tar xJ

(
	cd poppler-${POPPLER_VERSION}
	mkdir build && cd build
	cmake .. \
	  -DCMAKE_INSTALL_PREFIX=/tmp/poppler \
	  -DCMAKE_BUILD_TYPE=Release \
	  -DBUILD_SHARED_LIBS=OFF \
	  -DENABLE_LIBOPENJPEG=none \
	  -DENABLE_QT5=OFF \
	  -DENABLE_QT6=OFF \
	  -DENABLE_GLIB=OFF \
	  -DENABLE_BOOST=OFF \
	  -DENABLE_CPP=OFF \
	  -DENABLE_GPGME=OFF
	make -j$(nproc)
	make install
)

cp /tmp/poppler/bin/pdftotext $1
cp /tmp/poppler/bin/pdftoppm ${1%/*}/pdftoppm-${STACK}
